### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by dpastov** [TominoLP/2FA-API#4]
Could you please define the minimal Java version?

**Comment by TominoLP** [comment]
I'll be home again this evening and can make the change then

**Comment by dpastov** [comment]
Yes.
Imagine a server where we validate totp is 1 minute behind of real time. so we need to be able to set a window like checking code from -2 mins to now and to +2 mins.

**Comment by dpastov** [comment]
Great, it's because my server is most likely can't go higher than v8 and as far as I see your lib. requires higher version.

**Comment by TominoLP** [comment]
Yep, but should be able to Run on 1.8 i think, should Not be a big Problem

**Comment by dpastov** [comment]
```
   <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
```

OK, could you please check if it is save to set 8 as a compiler?

I have just tried mvn package with 8 and 1.8 and that did not help:

> java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=, offset=6

**Comment by dpastov** [comment]
> As of 3.0.1 java 11 is required. Latest java 8 version is 2.7.0.

OK, it's QRGen that is using Java 11.
I will see if I can use 2.7

**Comment by dpastov** [comment]
'''
[3F90:0163-0630] 05/05/2024 01:27:14 PM  HTTP JVM: java.lang.NoClassDefFoundError: org.apache.commons.codec.binary.Base32
[3F90:0165-0630] 05/05/2024 01:27:14 PM  HTTP JVM:      at de.tomino.AuthSys.generateSecretKey(AuthSys.java:51)
'''

Cant make it work, unfrotunatelly.

Could you please see if we can use Java8?

**Comment by TominoLP** [comment]
@dpastov works now on 1.8, tested 1.8 to 22

**Comment by dpastov** [comment]
great! thanks, it is odd but it did not work on my server (but that is an old IBM Domino server with Java 8). I will try to figure out why it did not run.
